import { useState, useEffect, useCallback, useMemo } from "react";
import { useTranslation } from "react-i18next";
import toast from "react-hot-toast";
import {
  getSubjects,
  createSubject,
  updateSubject,
  deleteSubject,
} from "../../../core/api/subjectService";
import {
  FiBook,
  FiSearch,
  FiPlus,
  FiX,
  FiCheck,
  FiTrash2,
  FiEdit2,
  FiCheckCircle,
} from "react-icons/fi";

const COLORS = [
  "#085041", "#3B82F6", "#8B5CF6", "#EC4899", "#F59E0B",
  "#EF4444", "#6366F1", "#14B8A6", "#1D9E75", "#0EA5E9",
];


export default function SubjectsListPage() {
  const { i18n } = useTranslation("common");
  const isFr = i18n.language === "fr";

  // ── State ──
  const [subjects, setSubjects] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [searchQuery, setSearchQuery] = useState("");

  // Form
  const [formMode, setFormMode] = useState(null);
  const [editingId, setEditingId] = useState(null);
  const [formName, setFormName] = useState("");
  const [formCode, setFormCode] = useState("");
  const [codeAutoGenerated, setCodeAutoGenerated] = useState(false);
  const [codeAnimating, setCodeAnimating] = useState(false);
  const [saving, setSaving] = useState(false);
  const [formErrors, setFormErrors] = useState({});

  // Delete
  const [deleteTarget, setDeleteTarget] = useState(null);
  const [deleting, setDeleting] = useState(false);

  // Success
  const [showSuccess, setShowSuccess] = useState(false);
  const [successName, setSuccessName] = useState("");

  // ── Filtered subjects ──
  const filteredSubjects = useMemo(() => {
    if (!searchQuery) return subjects;
    const q = searchQuery.toLowerCase();
    return subjects.filter(
      (s) =>
        s.name.toLowerCase().includes(q) ||
        (s.code || "").toLowerCase().includes(q)
    );
  }, [subjects, searchQuery]);

  // ── Load ──
  const loadSubjects = useCallback(async () => {
    try {
      setLoading(true);
      setError(null);
      const data = await getSubjects();
      setSubjects(Array.isArray(data) ? data : data?.subjects || data?.rows || []);
    } catch (err) {
      console.error("Failed to load subjects:", err);
      setError(isFr ? "Erreur de chargement" : "Failed to load subjects");
    } finally {
      setLoading(false);
    }
  }, [isFr]);

  useEffect(() => {
    loadSubjects();
  }, [loadSubjects]);

  // ── Auto-generate code from name ──
  useEffect(() => {
    if (formMode !== "create") {
      setCodeAutoGenerated(false);
      setCodeAnimating(false);
      return;
    }
    if (!formName.trim() || editingId) return;
    if (codeAutoGenerated) return;

    const generated = formName.trim().toUpperCase().slice(0, 3);
    if (!generated || generated === formCode) return;

    setCodeAutoGenerated(true);
    setCodeAnimating(true);
    setFormCode(generated);
    const timer = setTimeout(() => setCodeAnimating(false), 500);
    return () => clearTimeout(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [formName, formMode]);

  // ── Form helpers ──
  const resetForm = () => {
    setFormName("");
    setFormCode("");
    setCodeAutoGenerated(false);
    setCodeAnimating(false);
    setFormErrors({});
    setEditingId(null);
  };

  const openCreateForm = () => {
    resetForm();
    setFormMode("create");
    document.getElementById("formCard")?.scrollIntoView({ behavior: "smooth", block: "start" });
  };

  const openEditForm = (subject) => {
    setFormName(subject.name || "");
    setFormCode(subject.code || "");
    setCodeAutoGenerated(false);
    setCodeAnimating(false);
    setFormErrors({});
    setEditingId(subject.id);
    setFormMode("edit");
    document.getElementById("formCard")?.scrollIntoView({ behavior: "smooth", block: "start" });
  };

  const closeForm = () => {
    setFormMode(null);
    resetForm();
  };

  const validateForm = () => {
    const errs = {};
    if (!formName.trim()) errs.name = isFr ? "Le nom est requis" : "Name is required";
    setFormErrors(errs);
    return Object.keys(errs).length === 0;
  };

  const handleSave = async () => {
    if (!validateForm()) return;
    setSaving(true);
    try {
      const payload = {
        name: formName.trim(),
        code: formCode.trim().toUpperCase() || undefined,
      };

      if (editingId) {
        await updateSubject(editingId, payload);
        toast.success(isFr ? "Matière mise à jour" : "Subject updated");
      } else {
        await createSubject(payload);
        setSuccessName(formName.trim());
        setShowSuccess(true);
        toast.success(isFr ? "Matière créée" : "Subject created");
      }

      setFormMode(null);
      resetForm();
      loadSubjects();
    } catch (err) {
      const msg = err?.response?.data?.message || (isFr ? "Erreur" : "Failed to save");
      toast.error(msg);
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async () => {
    if (!deleteTarget) return;
    setDeleting(true);
    try {
      await deleteSubject(deleteTarget.id);
      toast.success(isFr ? "Matière supprimée" : "Subject deleted");
      setDeleteTarget(null);
      loadSubjects();
    } catch (err) {
      toast.error(err?.response?.data?.message || (isFr ? "Erreur" : "Error"));
    } finally {
      setDeleting(false);
    }
  };

  // ── Style classes ──
  const inputClass =
    "w-full h-[44px] px-3.5 border-[1.5px] border-surface-200 dark:border-surface-600 rounded-[10px] text-sm text-surface-800 dark:text-surface-100 bg-white dark:bg-surface-800 outline-none transition-all duration-200 focus:border-primary-600 focus:shadow-[0_0_0_3.5px_rgba(8,80,65,.08)] placeholder:text-surface-300 dark:placeholder:text-surface-500";
  const labelClass = "block text-[12.5px] font-bold text-surface-700 dark:text-surface-300 mb-1.5";

  // ── Loading ──
  if (loading) {
    return (
      <div className="max-w-[800px] mx-auto pb-16">
        <div className="animate-pulse space-y-4">
          <div className="h-8 bg-surface-100 dark:bg-surface-700 rounded-xl w-48" />
          <div className="h-64 bg-surface-100 dark:bg-surface-700 rounded-xl" />
        </div>
      </div>
    );
  }

  // ── Error ──
  if (error) {
    return (
      <div className="max-w-[800px] mx-auto pb-16 text-center py-20">
        <FiBook className="w-12 h-12 text-red-400 mx-auto mb-4" />
        <h2 className="font-display text-xl font-bold text-surface-800 dark:text-surface-100 mb-2">
          {isFr ? "Erreur de chargement" : "Loading error"}
        </h2>
        <p className="text-sm text-surface-400 mb-6">{error}</p>
        <button onClick={loadSubjects} className="h-10 px-5 rounded-lg bg-primary-900 text-white text-sm font-semibold hover:bg-primary-700 transition-colors">
          {isFr ? "Réessayer" : "Retry"}
        </button>
      </div>
    );
  }

  // ── Render ──
  return (
    <div className="max-w-[800px] mx-auto pb-16">
      {/* Success Overlay */}
      {showSuccess && (
        <div className="fixed inset-0 bg-black/45 backdrop-blur-sm z-50 flex items-center justify-center">
          <div className="bg-white dark:bg-surface-800 rounded-2xl p-10 text-center max-w-[420px] w-[90%] shadow-2xl animate-[scaleIn_0.35s_cubic-bezier(.34,1.56,.64,1)]">
            <div className="w-[68px] h-[68px] rounded-full flex items-center justify-center mx-auto mb-4"
              style={{ background: "rgba(8,80,65,0.08)", border: "2px solid rgba(8,80,65,0.2)" }}>
              <FiCheckCircle className="w-9 h-9" style={{ color: "#085041" }} strokeWidth={1.5} />
            </div>
            <h2 className="font-display text-xl font-bold text-surface-800 dark:text-surface-100 mb-1">
              {isFr ? "Matière enregistrée !" : "Subject saved!"}
            </h2>
            <p className="text-sm text-surface-400 mb-6">
              <strong>{successName}</strong>{" "}
              {isFr ? "a été ajoutée avec succès." : "has been added successfully."}
            </p>
            <div className="flex gap-3 justify-center">
              <button onClick={() => { setShowSuccess(false); openCreateForm(); }}
                className="h-10 px-5 rounded-lg border border-surface-200 dark:border-surface-600 text-surface-600 dark:text-surface-300 text-sm font-semibold hover:bg-surface-50 dark:hover:bg-surface-700 transition-colors">
                {isFr ? "Ajouter une autre" : "Add another"}
              </button>
              <button onClick={() => setShowSuccess(false)}
                className="h-10 px-5 rounded-lg text-white text-sm font-semibold" style={{ backgroundColor: "#085041" }}>
                {isFr ? "Terminé" : "Done"}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ── Header ── */}
      <div className="flex items-start justify-between flex-wrap gap-4 mb-6 animate-[fadeUp_0.4s_cubic-bezier(.16,1,.3,1)]">
        <div>
          <div className="flex items-center gap-2.5 mb-1">
            <div className="w-1 h-[26px] rounded-full" style={{ backgroundColor: "#085041" }} />
            <h1 className="font-display text-[26px] font-bold text-surface-900 dark:text-surface-100">
              {isFr ? "Matières" : "Subjects"}
            </h1>
          </div>
          <p className="text-[13.5px] text-surface-400 ml-3.5">
            {subjects.length} {isFr ? "matière" : "subject"}
            {subjects.length > 1 ? "s" : ""}
          </p>
        </div>
        <button onClick={openCreateForm}
          className="h-9 px-3.5 rounded-lg text-white text-xs font-bold flex items-center gap-1.5 shadow-md hover:-translate-y-0.5 transition-all"
          style={{ backgroundColor: "#085041", boxShadow: "0 4px 14px rgba(8,80,65,.22)" }}>
          <FiPlus className="w-3.5 h-3.5" strokeWidth={2.5} />
          {isFr ? "Ajouter" : "Add subject"}
        </button>
      </div>

      {/* ── Main Layout ── */}
      <div className="grid grid-cols-1 lg:grid-cols-[1fr_340px] gap-5 items-start">
        {/* ── Left: Subject List ── */}
        <div className="bg-white dark:bg-surface-800 rounded-xl border border-surface-100 dark:border-surface-700 shadow-sm overflow-hidden">
          {/* Search */}
          <div className="flex items-center gap-2.5 p-4 border-b border-surface-100 dark:border-surface-700">
            <div className="flex-1 flex items-center gap-2 bg-surface-50 dark:bg-surface-900 border border-surface-100 dark:border-surface-600 rounded-lg px-3 h-10">
              <FiSearch className="w-3.5 h-3.5 text-surface-400 flex-shrink-0" />
              <input value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)}
                placeholder={isFr ? "Rechercher une matière..." : "Search subjects..."}
                className="flex-1 border-none outline-none text-xs bg-transparent text-surface-800 dark:text-surface-100 placeholder:text-surface-400" />
            </div>
          </div>

          {/* Table / Empty */}
          {filteredSubjects.length === 0 ? (
            <div className="text-center py-14">
              <div className="w-16 h-16 rounded-full bg-surface-100 dark:bg-surface-700 flex items-center justify-center mx-auto mb-3">
                <FiBook className="w-7 h-7 text-surface-400" />
              </div>
              <h3 className="font-display text-lg font-bold text-surface-800 dark:text-surface-100 mb-1">
                {searchQuery
                  ? isFr ? "Aucun résultat" : "No results"
                  : isFr ? "Aucune matière" : "No subjects yet"}
              </h3>
              <p className="text-sm text-surface-400 mb-5">
                {searchQuery
                  ? isFr ? `Aucune matière ne correspond à "${searchQuery}"` : `No subjects match "${searchQuery}"`
                  : isFr ? "Ajoutez votre première matière." : "Add your first subject."}
              </p>
              {!searchQuery && (
                <button onClick={openCreateForm} className="h-9 px-4 rounded-lg text-white text-xs font-bold" style={{ backgroundColor: "#085041" }}>
                  <FiPlus className="w-3.5 h-3.5 inline mr-1.5" strokeWidth={2.5} />
                  {isFr ? "Ajouter une matière" : "Add subject"}
                </button>
              )}
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="bg-surface-50 dark:bg-surface-900">
                    <th className="text-left py-2.5 px-4 text-[10.5px] font-bold uppercase tracking-wider text-surface-400 border-b border-surface-100 dark:border-surface-700">
                      {isFr ? "Matière" : "Subject"}
                    </th>
                    <th className="text-left py-2.5 px-4 text-[10.5px] font-bold uppercase tracking-wider text-surface-400 border-b border-surface-100 dark:border-surface-700 w-16">
                      {isFr ? "Code" : "Code"}
                    </th>
                    <th className="py-2.5 px-4 border-b border-surface-100 dark:border-surface-700 w-16"></th>
                  </tr>
                </thead>
                <tbody>
                  {filteredSubjects.map((s) => {
                    const subjColor = s.color || COLORS[0];
                    return (
                      <tr key={s.id} onClick={() => openEditForm(s)}
                        className="group border-b border-surface-50 dark:border-surface-800 hover:bg-[rgba(8,80,65,.025)] dark:hover:bg-surface-900/30 transition-colors cursor-pointer">
                        <td className="py-3 px-4">
                          <div className="flex items-center gap-2.5">
                            <div className="w-[4px] h-9 rounded-full flex-shrink-0" style={{ backgroundColor: subjColor }} />
                            <div className="text-sm font-bold text-surface-800 dark:text-surface-100">{s.name}</div>
                          </div>
                        </td>
                        <td className="py-3 px-4">
                          {s.code ? (
                            <span className="text-[11px] font-mono font-semibold text-surface-500 bg-surface-50 dark:bg-surface-900 px-2 py-0.5 rounded-md border border-surface-100 dark:border-surface-700">
                              {s.code}
                            </span>
                          ) : (
                            <span className="text-[11px] text-surface-400">—</span>
                          )}
                        </td>
                        <td className="py-3 px-4 text-right">
                          <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                            <button onClick={(e) => { e.stopPropagation(); openEditForm(s); }}
                              className="w-7 h-7 rounded-lg border border-surface-100 dark:border-surface-600 bg-white dark:bg-surface-800 flex items-center justify-center hover:scale-110 transition-transform">
                              <FiEdit2 className="w-3 h-3 text-surface-400" />
                            </button>
                            <button onClick={(e) => { e.stopPropagation(); setDeleteTarget(s); }}
                              className="w-7 h-7 rounded-lg border border-surface-100 dark:border-surface-600 bg-white dark:bg-surface-800 flex items-center justify-center hover:scale-110 hover:border-red-200 hover:bg-red-50 transition-all">
                              <FiTrash2 className="w-3 h-3 text-surface-400 hover:text-red-500" />
                            </button>
                          </div>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </div>

        {/* ── Right: Form Card ── */}
        <div>
          <div id="formCard" className="bg-white dark:bg-surface-800 rounded-xl border border-surface-100 dark:border-surface-700 shadow-sm p-6 sticky top-6">
            {formMode ? (
              <>
                <h3 className="font-display text-lg font-bold text-surface-900 dark:text-surface-100 mb-1">
                  {formMode === "create"
                    ? isFr ? "Ajouter une matière" : "Add a subject"
                    : isFr ? `Modifier ${formName || "..."}` : `Edit ${formName || "..."}`}
                </h3>
                <p className="text-xs text-surface-400 mb-5">
                  {isFr
                    ? "Le coefficient se configure lors de l'assignation à une classe."
                    : "The coefficient is set when assigning to a class."}
                </p>

                {/* Name */}
                <div className="mb-3">
                  <label className={labelClass}>
                    {isFr ? "Nom" : "Name"} <span className="text-primary-600">*</span>
                  </label>
                  <input value={formName} onChange={(e) => setFormName(e.target.value)}
                    placeholder={isFr ? "Ex: Mathématiques" : "e.g. Mathematics"}
                    className={`${inputClass} ${formErrors.name ? "!border-red-500" : ""}`} autoFocus />
                  {formErrors.name && <p className="text-xs text-red-500 mt-1">{formErrors.name}</p>}
                </div>

                {/* Code */}
                <div className="mb-3">
                  <label className={labelClass}>
                    {isFr ? "Code" : "Code"}
                    <span className="text-surface-300 font-normal ml-1">({isFr ? "auto" : "auto"})</span>
                  </label>
                  <div className="relative">
                    <input value={formCode}
                      onChange={(e) => { setFormCode(e.target.value.toUpperCase()); setCodeAutoGenerated(false); }}
                      placeholder={isFr ? "Ex: MATH" : "e.g. MATH"} maxLength={8}
                      className={`${inputClass} ${codeAnimating ? "!border-primary-400 !shadow-[0_0_0_3.5px_rgba(8,80,65,.12)]" : ""} transition-all duration-300 pr-8`} />
                    {codeAnimating && (
                      <div className="absolute right-2.5 top-1/2 -translate-y-1/2">
                        <div className="w-4 h-4 rounded-full border-2 border-primary-200 border-t-primary-600 animate-spin" />
                      </div>
                    )}
                  </div>
                  <div className="flex items-center gap-2 mt-1.5">
                    <p className="text-[11.5px] text-surface-400">
                      {isFr ? "Généré automatiquement depuis le nom" : "Auto-generated from the name"}
                    </p>
                    {codeAutoGenerated && !codeAnimating && formCode && (
                      <span className="text-[10px] font-semibold text-primary-600 bg-primary-50 dark:bg-primary-900/20 px-2 py-0.5 rounded-full border border-primary-200 dark:border-primary-800 animate-[fadeIn_0.3s_ease]">
                        ✨ Auto
                      </span>
                    )}
                  </div>
                </div>

                {/* Live Preview */}
                {formName.trim() && (
                  <div className="mb-4 p-3.5 rounded-xl border border-primary-100 dark:border-primary-900/30 bg-primary-50/50 dark:bg-primary-900/10 animate-[fadeUp_0.35s_cubic-bezier(.16,1,.3,1)]">
                    <div className="flex items-center gap-3">
                      <div className="w-9 h-9 rounded-xl flex items-center justify-center text-sm font-extrabold text-white flex-shrink-0"
                        style={{ backgroundColor: COLORS[formName.length % COLORS.length] }}>
                        {formCode || "?"}
                      </div>
                      <div>
                        <div className="text-sm font-bold text-surface-800 dark:text-surface-100">{formName}</div>
                        {formCode && <div className="text-[11px] font-mono text-surface-400">{formCode}</div>}
                      </div>
                    </div>
                  </div>
                )}

                {/* Buttons */}
                <div className="flex flex-col gap-2.5">
                  <button onClick={handleSave} disabled={saving}
                    className="w-full h-[46px] rounded-xl text-white text-sm font-bold flex items-center justify-center gap-2 shadow-md disabled:opacity-55 disabled:cursor-not-allowed transition-all hover:-translate-y-0.5"
                    style={{ backgroundColor: "#085041", boxShadow: "0 4px 14px rgba(8,80,65,.22)" }}>
                    {saving ? (
                      <div className="w-4 h-4 rounded-full border-2 border-white/30 border-t-white animate-spin" />
                    ) : (
                      <FiCheck className="w-4 h-4" strokeWidth={2.5} />
                    )}
                    {saving
                      ? isFr ? "Enregistrement..." : "Saving..."
                      : formMode === "edit"
                        ? isFr ? "Mettre à jour" : "Update"
                        : isFr ? "Enregistrer" : "Save"}
                  </button>
                  <button onClick={closeForm}
                    className="w-full h-[46px] rounded-xl border-2 border-surface-200 dark:border-surface-600 text-surface-700 dark:text-surface-300 text-sm font-semibold hover:bg-surface-50 dark:hover:bg-surface-700 transition-colors flex items-center justify-center gap-1.5">
                    <FiX className="w-4 h-4" />
                    {isFr ? "Annuler" : "Cancel"}
                  </button>
                </div>
              </>
            ) : (
              <div className="text-center py-8">
                <div className="w-14 h-14 rounded-full bg-surface-100 dark:bg-surface-700 flex items-center justify-center mx-auto mb-3">
                  <FiBook className="w-6 h-6 text-surface-400" />
                </div>
                <h3 className="font-semibold text-surface-800 dark:text-surface-100 mb-1">
                  {isFr ? "Ajouter une matière" : "Add a subject"}
                </h3>
                <p className="text-xs text-surface-400 mb-4">
                  {isFr
                    ? "Le coefficient se configure dans l'assignation aux classes."
                    : "Coefficient is set when assigning to classes."}
                </p>
                <button onClick={openCreateForm}
                  className="h-9 px-4 rounded-lg bg-primary-900 text-white text-xs font-bold hover:-translate-y-0.5 transition-transform">
                  <FiPlus className="w-3.5 h-3.5 inline mr-1.5" strokeWidth={2.5} />
                  {isFr ? "Nouvelle matière" : "New subject"}
                </button>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* ── Delete Modal ── */}
      {deleteTarget && (
        <div className="fixed inset-0 bg-black/45 backdrop-blur-sm z-50 flex items-center justify-center">
          <div className="bg-white dark:bg-surface-800 rounded-2xl p-6 max-w-[400px] w-[90%] shadow-2xl">
            <h3 className="font-display text-lg font-bold text-surface-800 dark:text-surface-100 mb-2">
              {isFr ? "Confirmer la suppression" : "Confirm deletion"}
            </h3>
            <p className="text-sm text-surface-600 dark:text-surface-300 mb-5">
              {isFr
                ? `Êtes-vous sûr de vouloir supprimer "${deleteTarget.name}" ?`
                : `Are you sure you want to delete "${deleteTarget.name}"?`}
            </p>
            <div className="flex gap-3 justify-end">
              <button onClick={() => setDeleteTarget(null)}
                className="h-10 px-5 rounded-lg border border-surface-200 dark:border-surface-600 text-surface-600 dark:text-surface-300 text-sm font-semibold hover:bg-surface-50 dark:hover:bg-surface-700 transition-colors">
                {isFr ? "Annuler" : "Cancel"}
              </button>
              <button onClick={handleDelete} disabled={deleting}
                className="h-10 px-5 rounded-lg bg-red-500 text-white text-sm font-bold flex items-center gap-2 disabled:opacity-55">
                {deleting && <div className="w-3.5 h-3.5 rounded-full border-2 border-white/30 border-t-white animate-spin" />}
                {isFr ? "Supprimer" : "Delete"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}